version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/Mental_health_frontend
    ports:
      - '3000:3000'
    image: app:react
    container_name: frontend
    command: npm start
